#!/bin/bash
# labels.en.sh — English UI labels for generate-report.sh
LABEL_TOTAL_PHASES="Total Phases"
LABEL_DURATION="Duration"
LABEL_COMPLETED="Completed"
LABEL_PROGRESS="Progress"
LABEL_TIMELINE="Timeline"
LABEL_PHASE_INDEX="Phase Index"
LABEL_DETAIL_LINK="Detail Log →"
LABEL_GENERATED="Generated"
LABEL_ACTIONS="Actions"
LABEL_RESULTS="Results"
LABEL_DECISIONS="Decisions"
LABEL_NEXT_STEPS="Next Steps"
LABEL_USER_AVATAR="U"
LABEL_AI_AVATAR="C"
LABEL_ACTIONS_BADGE="performed"
LABEL_RESULTS_BADGE="output"
LABEL_DECISIONS_BADGE="decided"
LABEL_HTML_LANG="en"
LABEL_FONT_IMPORT=""
LABEL_FONT_FAMILY="system-ui, -apple-system, sans-serif"
