#!/bin/bash
# labels.ko.sh — Korean UI labels for generate-report.sh
LABEL_TOTAL_PHASES="전체 페이즈"
LABEL_DURATION="기간"
LABEL_COMPLETED="완료"
LABEL_PROGRESS="진행률"
LABEL_TIMELINE="타임라인"
LABEL_PHASE_INDEX="페이즈 목록"
LABEL_DETAIL_LINK="상세 로그 →"
LABEL_GENERATED="생성"
LABEL_ACTIONS="수행 작업"
LABEL_RESULTS="결과"
LABEL_DECISIONS="결정"
LABEL_NEXT_STEPS="다음 단계"
LABEL_USER_AVATAR="U"
LABEL_AI_AVATAR="C"
LABEL_ACTIONS_BADGE="수행 작업"
LABEL_RESULTS_BADGE="결과"
LABEL_DECISIONS_BADGE="결정"
LABEL_HTML_LANG="ko"
LABEL_FONT_IMPORT="<link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@300;400;500;700;900&display=swap\" rel=\"stylesheet\">"
LABEL_FONT_FAMILY="'Noto Sans KR', sans-serif"
